[package]
name = "open-f1-client-macros"
version.workspace = true
edition.workspace = true

[dependencies]
convert_case = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lib]
proc-macro = true
